### ISSUE TITLE
FileExistsError: ../Primers/ does not exist or is not 

### ISSUE THREAD

**Issue by c1a1o1** [davda54/generating-music#1]
E:\Users\Raytine\Anaconda3\python.exe "F:/music/generating-music-master/Generative Model/Chord_Predictor/chord_generate.py"
WARNING: You have a CUDA device, so you should probably run with --cuda True
E:\Users\Raytine\Anaconda3\lib\site-packages\torch\serialization.py:367: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
E:\Users\Raytine\Anaconda3\lib\site-packages\torch\serialization.py:367: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
E:\Users\Raytine\Anaconda3\lib\site-packages\torch\serialization.py:367: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "F:/music/generating-music-master/Generative Model/Chord_Predictor/chord_generate.py", line 84, in <module>
    output = generate_chords(args.model, args.primer, args.cuda, args.priming_length, args.length, args.temperature, args.n_primes)
  File "F:/music/generating-music-master/Generative Model/Chord_Predictor/chord_generate.py", line 10, in generate_chords
    loader = Loader("../Primers/" + primer)
  File "..\utils.py", line 69, in __init__
    if not file.is_file(): raise FileExistsError(self.filename + " does not exist or is not a file, please add a valid training and validation file, or priming song to the parameters")
FileExistsError: ../Primers/ does not exist or is not a file, please add a valid training and validation file, or priming song to the parameters

Process finished with exit code 1

**Comment by davda54** [comment]
Thanks for raising this issue, I have noticed some files were missing. Please try to run the program with an argument "--primer piano.mus", does it work now?

**Comment by c1a1o1** [comment]
This is a great code, can you provide more details about training data and test data? It is currently not working

**Comment by c1a1o1** [comment]
C:\Users\caocao\Anaconda3\python.exe "D:/work/work11/generating-music-master/Generative Model/Chord_Predictor/chord_generate.py" --cuda True
C:\Users\caocao\Anaconda3\lib\site-packages\torch\serialization.py:367: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\caocao\Anaconda3\lib\site-packages\torch\serialization.py:367: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\caocao\Anaconda3\lib\site-packages\torch\serialization.py:367: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
..\Chord_Predictor\lstm_model.py:51: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  self.hidden = (Variable(nn.init.xavier_uniform(weight.new(self.n_layers, batch_size, self.hidden_size))),
..\Chord_Predictor\lstm_model.py:52: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  Variable(nn.init.xavier_uniform(weight.new(self.n_layers, batch_size, self.hidden_size))))
Traceback (most recent call last):
  File "D:/work/work11/generating-music-master/Generative Model/Chord_Predictor/chord_generate.py", line 84, in <module>
    output = generate_chords(args.model, args.primer, args.cuda, args.priming_length, args.length, args.temperature, args.n_primes)
  File "D:/work/work11/generating-music-master/Generative Model/Chord_Predictor/chord_generate.py", line 34, in generate_chords
    model.repackage_hidden()
  File "..\Chord_Predictor\lstm_model.py", line 70, in repackage_hidden
    self.__repackage_hidden(self.hidden)
  File "..\Chord_Predictor\lstm_model.py", line 67, in __repackage_hidden
    return tuple(self.__repackage_hidden(v) for v in h)
  File "..\Chord_Predictor\lstm_model.py", line 67, in <genexpr>
    return tuple(self.__repackage_hidden(v) for v in h)
  File "..\Chord_Predictor\lstm_model.py", line 67, in __repackage_hidden
    return tuple(self.__repackage_hidden(v) for v in h)
  File "..\Chord_Predictor\lstm_model.py", line 67, in <genexpr>
    return tuple(self.__repackage_hidden(v) for v in h)
  File "..\Chord_Predictor\lstm_model.py", line 67, in __repackage_hidden
    return tuple(self.__repackage_hidden(v) for v in h)
  File "..\Chord_Predictor\lstm_model.py", line 67, in <genexpr>
    return tuple(self.__repackage_hidden(v) for v in h)
  File "..\Chord_Predictor\lstm_model.py", line 67, in __repackage_hidden
    return tuple(self.__repackage_hidden(v) for v in h)
  File "..\Chord_Predictor\lstm_model.py", line 67, in <genexpr>
    return tuple(self.__repackage_hidden(v) for v in h)
  File "..\Chord_Predictor\lstm_model.py", line 67, in __repackage_hidden
    return tuple(self.__repackage_hidden(v) for v in h)
  File "C:\Users\caocao\Anaconda3\lib\site-packages\torch\tensor.py", line 360, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

**Comment by davda54** [comment]
There are currently no training data, as they were quite large to be included. The idea is that you should use [Analyzer](https://github.com/davda54/generating-music/tree/master/Analyzer) and its "Convert Batch" button to transform your own MIDI dataset into the .mus format used by the generative model.

But I see that it's an unnecessarily difficult process if you just want to give it a try -- that's why I've added a [small dataset of Beatles songs](https://github.com/davda54/generating-music/tree/master/Generative%20Model/Data/beatles_batch.mus) to the Data directory, so you can try to train a new model :) (don't expect miracles from such a small dataset, but I hope it won't at least throw an exception).

For example try to run `music_train.py` with `--train_file beatles_batch.mus --val_file beatles_batch.mus --event_emsize 64 --nhid 64 --seq_len 64 --layers 2 --batch_size 64`

**Comment by davda54** [comment]
Sorry, but I can't reproduce the `TypeError: iteration over a 0-d tensor` error. What version of PyTorch are you using? I'm using version 0.3 (because newer versions don't have support for my GPU), so there may be a problem with backward compatibility? Anyway you should always specify a primer when generating.
